#include <numeric>
#include "problemes.h"
#include "fibonacci.h"

typedef unsigned long long nombre;
typedef std::vector<nombre> vecteur;

ENREGISTRER_PROBLEME(2, "Even Fibonacci numbers") {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    // By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // 
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    // find the sum of the even-valued terms.
    Fibonacci<nombre> fibonacci(4000000L);
    nombre solution = 0;
    for (const auto t: fibonacci) {
        if (t % 2 == 0) {
            solution += t;
        }
    }

    return std::to_string(solution);
}
